Snippetgrab/Snippetgrab/Controllers/MessageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Snippetgrab.Models;
using SnippetgrabClasslibrary.Data;
using SnippetgrabClasslibrary.Logic;
using SnippetgrabClasslibrary.Models;

namespace Snippetgrab.Controllers
{
    public class MessageController : Controller
    {
        UserRepository _userRepo = new UserRepository(new UserMsSqlContext());
        MessageRepository _messageRepo = new MessageRepository(new MessageMsSqlContext());

        // GET: Message
        public ActionResult Index()
        {
            if ((int) Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            var userId = (int) Session["UserId"];
            UserModel um = new UserModel();
            um.SetActiveUser(userId);
            um.GetMessages();
            return View(um);
        }

        public ActionResult Detail(int MessageId)
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            UserModel um = new UserModel();
            um.GetMessage(MessageId);
            return View(um);
        }

        public ActionResult Add()
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            UserModel um = new UserModel();        
            um.GetAllsUser();    
            return View(um);
        }

        [HttpPost]
        public ActionResult Add(string MessageText, string Receipent)
        {
            var userId = (int) Session["UserId"];
            var receipent = _userRepo.GetUserByEmail(Receipent);
            var newMessage = new Message(MessageText, userId, receipent.ID);
            _messageRepo.AddMessage(newMessage);
            return RedirectToAction("Index");
        }

    }
}

Snippetgrab/Snippetgrab/Controllers/ProblemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Snippetgrab.Models;
using SnippetgrabClasslibrary.Data;
using SnippetgrabClasslibrary.Logic;
using SnippetgrabClasslibrary.Models;

namespace Snippetgrab.Controllers
{
    public class ProblemController : Controller
    {
        private readonly TagRepository _tagRepo = new TagRepository(new TagMsSqlContext());
        private readonly CommentRepository _commentRepo = new CommentRepository(new CommentMsSqlContext());
        private readonly ProblemRepository _problemRepository = new ProblemRepository(new ProblemMsSqlContext());

        // GET: Problem
        public ActionResult Index()
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            ProblemModel pm = new ProblemModel();
            return View(pm);
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            ProblemModel pm = new ProblemModel();
            pm.Getproblem(id);
            return View(pm);
        }

        public ActionResult Add()
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            Problem p = new Problem();
            p.Tags = _tagRepo.GetAll();
            return View(p);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(Problem newProblem, FormCollection form)
        {
            ProblemModel pm = new ProblemModel();

            if (ModelState.IsValid)
            {
                newProblem.AuthorID = (int)Session["UserID"];
                newProblem.Points = 1;
                newProblem.IsSolved = false;
                var AllStrings = form["checkboxTag"].Split(',');
                foreach (string item in AllStrings)
                {
                    int value = int.Parse(item);
                    var tag = _tagRepo.GetTagById(value);
                    newProblem.Tags.Add(tag);
                }
                pm.AddProblem(newProblem);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult PostComment(int problemId, string commentText)
        {
            var userId = (int)Session["UserId"];
            Comment newComment = new Comment(commentText, 0, userId, problemId);
            _commentRepo.AddComment(newComment);
            ProblemModel pm = new ProblemModel();
            pm.Getproblem(problemId);
            return RedirectToAction("Detail", new { id = problemId });
        }

        [HttpPost]
        public ActionResult ChangePointProblem(int problemId, string point)
        {
            switch (point)
            {
                case "+":
                    _problemRepository.ChangePoint(problemId, 1);
                    break;
                case "-":
                    _problemRepository.ChangePoint(problemId, 0);
                    break;
                default:
                    return RedirectToAction("Detail", new { id = problemId });
            }
            
            return RedirectToAction("Detail", new { id = problemId });
        }

        public ActionResult ChangePointComment(int problemId, string point, int commentId)
        {
            switch (point)
            {
                case "+":
                    _commentRepo.ChangePoint(commentId, 1);
                    break;
                case "-":
                    _commentRepo.ChangePoint(commentId, 0);
                    break;
                default:
                    return RedirectToAction("Detail", new { id = problemId });
            }

            return RedirectToAction("Detail", new { id = problemId });
        }
    }
}

Snippetgrab/Snippetgrab/Controllers/SnippetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Snippetgrab.Models;
using SnippetgrabClasslibrary.Data;
using SnippetgrabClasslibrary.Logic;
using SnippetgrabClasslibrary.Models;

namespace Snippetgrab.Controllers
{
    
    public class SnippetController : Controller
    {
        private readonly TagRepository _tagRepo = new TagRepository(new TagMsSqlContext());
        private readonly SnippetRepository _snippetRepo = new SnippetRepository(new SnippetMsSqlContext());

        [HttpGet]
        public ActionResult Index()
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            SnippetModel sm = new SnippetModel();
            return View(sm);
        }

        [HttpGet]
        public ActionResult Add()
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            Snippet s = new Snippet();
            s.Tags = _tagRepo.GetAll();
            return View(s);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(Snippet newSnippet, FormCollection form)
        {
            SnippetModel sm = new SnippetModel();

            if (ModelState.IsValid)
            {
                newSnippet.Points = 1;
                if (form["checkboxTag"] == null)
                {
                    ViewBag.ErrorMessage = "No tags selected";
                    return RedirectToAction("Add");
                }

                 newSnippet.AuthorID = (int)Session["UserID"];
                
                var AllStrings = form["checkboxTag"].Split(',');
                foreach (string item in AllStrings)
                {
                    int value = int.Parse(item);
                    var tag = _tagRepo.GetTagById(value);
                    newSnippet.Tags.Add(tag);
                }
                sm.AddSnippet(newSnippet);
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            if ((int)Session["UserID"] == -1)
            {
                return RedirectToAction("Login", "User");
            }

            SnippetModel sm = new SnippetModel();
            sm.GetSnippet(id);
            return View(sm);
        }

        [HttpPost]
        public ActionResult ChangePoint(int snippetId, string point)
        {
            switch (point)
            {
                case "+":
                    _snippetRepo.ChangePoint(snippetId, 1);
                    break;
                case "-":
                    _snippetRepo.ChangePoint(snippetId, 0);
                    break;
                default:
                    return RedirectToAction("Detail", new { id = snippetId });
                    break;
            }

            return RedirectToAction("Detail", new { id = snippetId });
        }
    }
}

Snippetgrab/Snippetgrab/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Snippetgrab</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>

</head>
@if (ViewBag.ErrorMessage != null)
{
    <script>
        alert('@ViewBag.ErrorMessage');
    </script>
}
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Snippetgrab", "Home", "User", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Snippets", "Index", "Snippet", new {area = ""}, new {@class = "navbar-brand"})</li>
                <li>@Html.ActionLink("Problems", "Index", "Problem", new {area = ""}, new {@class = "navbar-brand"})</li>
                <li>@Html.ActionLink("Messages", "Index", "Message", new {area = ""}, new {@class = "navbar-brand"})</li>
                @{
                    if ((int) Session["UserId"] != -1)
                    {
                        <li style="position: absolute; right: 110px">@Html.ActionLink("Account", "Detail", "User", new {area = ""}, new {@class = "navbar-brand"})</li>
                        <li style="position: absolute; right: 20px">@Html.ActionLink("Uitloggen", "LogIn", "User", new {area = ""}, new {@class = "navbar-brand"})</li>
                    }
                }
            </ul>
        </div>
    </div>
</div>

<div class="container body-content">
    @RenderBody()
    <br/>
    <br/>
    <br/>
    <footer class="navbar navbar-fixed-bottom">

        <hr/>
        <p class="text-center">&copy; @DateTime.Now.Year - Snippetgrab <span class="text-info">Made by: Max Meijer </span></p>
    </footer>
</div>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/Main.js"></script>
</body>
</html>